name: artifact

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * 1-6'

jobs:
  build-go:
    name: Build Go
    runs-on: ubuntu-latest
    env:
      FILE_NAME: hello-server
    steps:

    - name: Checkout Go Code
      uses: actions/checkout@v2

    - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
      run: go build ${{ env.FILE_NAME }}.go

    - name: Build ${{ env.FILE_NAME }} for windows-latest
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

    - name: Upload artifact for Linux
      uses: actions/upload-artifact@v3
      with: 
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Upload artifact for Windows
      uses: actions/upload-artifact@v3
      with: 
        name: windows
        path: ./${{ env.FILE_NAME }}.exe
      
  download-and-run-linux:
    name: Download and run Linux
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Download Linux
        uses: actions/download-artifact@v4
        with:
          name: linux

      - name: List files
        run: ls -la

      - name: Make run exe
        run: chmod +x ./run.sh

      - name: Run
        run: ./run.sh

  download-only-windows:
    name: Download Windows
    runs-on: windows-latest
    needs: build-go
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Download Windows
        uses: actions/download-artifact@v4
        with:
          name: windows

      - name: List files
        run: dir 
